sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t eyearian/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true eyearian/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-682052465725"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $access_key_id
  secret_access_key:
    secure: $secret_access_key