sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t eyearian/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true eyearian/docker-react npm run test